main: com.github.escapemc.arenaplugin.Main
name: ArenaPlugin
version: 1.0.0
author: EscapeMC
description: A plugin made for Arenas or Dueling.
commands:
  arena_setspawn:
    description: Sets the spawn for the BlueTeam.
    default: false
  arena_team:
    description: Deals with the teams function of ArenaPlugin.
    default: false
  arena_start:
    aliases: [astart]
    description: Starts the arena match.
    default: false